### PR TITLE
add new ff

### PR DESCRIPTION
**Pull request by ArtemRomanov-FT**

### CODE REVIEW

**Comment by fivetran-github-worker** [comment]
@ArtemRomanov-FT 
File engineering/feature_flag/json/resources/AccountTimezoneForAppleSearchAds.json contains the following errors:
 The field 'include' contains duplicated values

**Comment by ArtemRomanov-FT** [comment]
@ArtemRomanov-FT 
File engineering/feature_flag/json/resources/AccountTimezoneForAppleSearchAds.json contains the following errors:
 The field 'description' is missed
	- The field 'include' contains duplicated valuesFile engineering/feature_flag/json/resources/AdditionalRequestBeforeSyncForGSheets.json contains the following errors:
 The field 'type' is missed
	- The field 'include' contains duplicated values

**Comment by ArtemRomanov-FT** [comment]
@ArtemRomanov-FT 
**File engineering/feature_flag/json/resources/AccountTimezoneForAppleSearchAds.json** contains the following errors:
	- The field 'description' is missed
	- The field 'include' contains duplicated values**File engineering/feature_flag/json/resources/AdditionalRequestBeforeSyncForGSheets.json** contains the following errors:
	- The field 'type' is missed
	- The field 'include' contains duplicated values

**Comment by ArtemRomanov-FT** [comment]
@ArtemRomanov-FT 
**File engineering/feature_flag/json/resources/AccountTimezoneForAppleSearchAds.json** contains the following errors:
	- The field 'description' is missed
	- The field 'include' contains duplicated values

**File engineering/feature_flag/json/resources/AdditionalRequestBeforeSyncForGSheets.json** contains the following errors:
	- The field 'type' is missed
	- The field 'include' contains duplicated values

**Comment by ArtemRomanov-FT** [comment]
**File engineering/feature_flag/json/resources/AccountTimezoneForAppleSearchAds.json** contains the following errors:
	- The field 'description' is missed
	- The field 'include' contains duplicated values

**File engineering/feature_flag/json/resources/AdditionalRequestBeforeSyncForGSheets.json** contains the following errors:
	- The field 'type' is missed
	- The field 'include' contains duplicated values

**Comment by ArtemRomanov-FT** [comment]
**File engineering/feature_flag/json/resources/AccountSettingsBrowserSessionTimeout.json** contains the following errors:
	- The field 'include' contains duplicated values

**File engineering/feature_flag/json/resources/AdditionalRequestBeforeSyncForGSheets.json** contains the following errors:
	- The field 'type' is missed
	- The field 'include' contains duplicated values

**Comment by ArtemRomanov-FT** [comment]
**File engineering/feature_flag/json/resources/AccountSettingsBrowserSessionTimeout.json** contains the following errors:
	- The field 'include' contains duplicated values

**File engineering/feature_flag/json/resources/AccountTimezoneForAppleSearchAds.json** contains the following errors:
	- The field 'include' contains duplicated values

**File engineering/feature_flag/json/resources/AdditionalRequestBeforeSyncForGSheets.json** contains the following errors:
	- The field 'type' is missed
	- The field 'include' contains duplicated values

**Comment by ArtemRomanov-FT** [comment]
**File engineering/feature_flag/json/resources/AdditionalRequestBeforeSyncForGSheets.json** contains the following errors:
	- The field 'include' contains duplicated values

**Pull request closed without merging**
