### PR TITLE
Test1

### PR DESCRIPTION
**Pull request by ArtemRomanov-FT**

### CODE REVIEW

**Comment by ArtemRomanov-FT** [comment]
**File engineering/feature_flag/json/resources/AdditionalRequestBeforeSyncForGSheets.json** contains the following errors:
	- The field 'include' contains duplicated values

**Comment by ArtemRomanov-FT** [comment]
**File engineering/feature_flag/json/resources/AccountSettingsBrowserSessionTimeout.json** contains the following errors:
	-  The field 'issues' does not contain any tickets associated with the feature flag

**File engineering/feature_flag/json/resources/AdditionalRequestBeforeSyncForGSheets.json** contains the following errors:
	- The field 'issues' is missed
	-  The field 'issues' does not contain any tickets associated with the feature flag
	- The field 'include' contains duplicated values

**Comment by ArtemRomanov-FT** [comment]
**File engineering/feature_flag/json/resources/AdditionalRequestBeforeSyncForGSheets.json** contains the following errors:
	- The field 'include' contains duplicated values

**Comment by ArtemRomanov-FT** [comment]
**File engineering/feature_flag/json/resources/AdditionalRequestBeforeSyncForGSheets.json** contains the following errors:
	- The field 'include' contains duplicated values

**Comment by ArtemRomanov-FT** [comment]
**File engineering/feature_flag/json/resources/AdditionalRequestBeforeSyncForGSheets1.json** contains the following errors:
	- The field 'include' contains duplicated values

**Comment by ArtemRomanov-FT** [comment]
**File engineering/feature_flag/json/resources/AccountSettingsBrowserSessionTimeout.json** contains the following errors:
	- The field 'type' is empty
	-  The field 'issues' does not contain any tickets associated with the feature flag

**File engineering/feature_flag/json/resources/AccountTimezoneForAppleSearchAds.json** contains the following errors:
	- The field 'type' is missed
	- The field 'include' contains duplicated values

**File engineering/feature_flag/json/resources/ActiveVolumeLongQueryTimeout.json** contains the following errors:
	- The field 'description' is empty
	- The field 'issues' is missed
	-  The field 'issues' does not contain any tickets associated with the feature flag
	- The field 'exclude' contains duplicated values

**Comment by fivetran-github-worker** [comment]
**File engineering/feature_flag/json/resources/AccountSettingsBrowserSessionTimeout.json** contains the following errors:
	- The field 'type' is empty
	-  The field 'issues' does not contain any tickets associated with the feature flag

**File engineering/feature_flag/json/resources/AccountTimezoneForAppleSearchAds.json** contains the following errors:
	- The field 'type' is missed
	- The field 'include' contains duplicated values

**File engineering/feature_flag/json/resources/ActiveVolumeLongQueryTimeout.json** contains the following errors:
	- The field 'description' is empty
	- The field 'issues' is missed
	-  The field 'issues' does not contain any tickets associated with the feature flag
	- The field 'exclude' contains duplicated values

**Comment by ArtemRomanov-FT** [comment]
**File engineering/feature_flag/json/resources/AccountSettingsBrowserSessionTimeout.json** contains the following errors:
	- The field 'type' is empty
	-  The field 'issues' does not contain any tickets associated with the feature flag

**File engineering/feature_flag/json/resources/AccountTimezoneForAppleSearchAds.json** contains the following errors:
	- The field 'type' is missed
	- The field 'include' contains duplicated values

**File engineering/feature_flag/json/resources/ActiveVolumeLongQueryTimeout.json** contains the following errors:
	- The field 'description' is empty
	- The field 'issues' is missed
	-  The field 'issues' does not contain any tickets associated with the feature flag
	- The field 'exclude' contains duplicated values

**Comment by fivetran-github-worker** [comment]
body

**Comment by ArtemRomanov-FT** [comment]
closed due to changes in notification conditions

**Pull request closed without merging**
